### Lab: Introduction to Python

In [46]:
import numpy as np
import pandas as pd
import plotly.offline as py
import plotly.graph_objs as go
#download_plotlyjs, init_notebook_mode, plot, iplot
py.init_notebook_mode(connected=True)

In [8]:
x = pd.Series([1,3,2,5])
x

0    1
1    3
2    2
3    5
dtype: int64

In [9]:
x = pd.Series([1, 6, 2])
x

0    1
1    6
2    2
dtype: int64

In [10]:
y = pd.Series([1, 4, 3])
y

0    1
1    4
2    3
dtype: int64

In [12]:
x + y

0     2
1    10
2     5
dtype: int64

In [21]:
x = np.matrix([[1,2],[3,4]]).T
x

matrix([[1, 3],
        [2, 4]])

In [22]:
np.sqrt(x)

matrix([[ 1.        ,  1.73205081],
        [ 1.41421356,  2.        ]])

In [30]:
np.power(x,2)

matrix([[ 1,  9],
        [ 4, 16]])

In [37]:
y = np.random.normal(size=100)
y.mean()


-0.10457048854994419

In [38]:
y.var()


1.0043329607213056

In [40]:
np.sqrt(y.var())

1.0021641386126854

In [41]:
y.std()

1.0021641386126854

In [62]:
x = np.random.normal(size=100)
y = np.random.normal(size=100)


In [50]:
x

101.63766204156828

In [57]:
traces = []
traces.append(go.Scatter(x=x, y=y, opacity=1, mode="markers"))
py.iplot(traces)

In [68]:
traces = []
traces.append(go.Histogram(x=x, opacity=0.50))
traces.append(go.Histogram(x=y, opacity=0.50))
layout = go.Layout(barmode='overlay')
fig = go.Figure(data=traces, layout=layout)

py.iplot(fig)

In [59]:
x = range(1,10+1)
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [70]:
auto = pd.read_csv("auto.csv")

In [71]:
auto.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [72]:
auto.columns

Index([u'mpg', u'cylinders', u'displacement', u'horsepower', u'weight',
       u'acceleration', u'year', u'origin', u'name'],
      dtype='object')

In [76]:
traces = []
traces.append(go.Scatter(x=auto["cylinders"].values, y=auto["mpg"].values, mode="markers"))
#traces.append(go.Histogram(x=y, opacity=0.50))
layout = go.Layout(barmode='overlay')
fig = go.Figure(data=traces, layout=layout)

py.iplot(fig)

In [77]:
traces = []
#traces.append(go.Scatter(x=auto["cylinders"].values, y=auto["mpg"].values, mode="markers"))
traces.append(go.Histogram(x=auto["mpg"].values, opacity=0.50))
layout = go.Layout(barmode='overlay')
fig = go.Figure(data=traces, layout=layout)

py.iplot(fig)

In [80]:
auto.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  397.000000  397.000000    397.000000   397.000000    397.000000   
mean    23.515869    5.458438    193.532746  2970.261965     15.555668   
std      7.825804    1.701577    104.379583   847.904119      2.749995   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.000000  2223.000000     13.800000   
50%     23.000000    4.000000    146.000000  2800.000000     15.500000   
75%     29.000000    8.000000    262.000000  3609.000000     17.100000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

             year      origin  
count  397.000000  397.000000  
mean    75.994962    1.574307  
std      3.690005    0.802549  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000